"""Seed data: ~200 Danish folkeskole math problems (3.-6. klasse)."""

import logging

from app.models.db import MathProblem

logger = logging.getLogger(__name__)

PROBLEMS = [
    # =========================================================================
    # ADDITION (25 problems)
    # =========================================================================
    # Difficulty 1 (3. klasse)
    {"topic": "addition", "subtopic": "simpel", "difficulty": 1, "grade_level": 3,
     "text": "Regn ud: 24 + 15", "type": "calculation", "correct_answer": "39",
     "hints": ["Start med enerne: 4 + 5"], "tags": "mental_matematik"},
    {"topic": "addition", "subtopic": "simpel", "difficulty": 1, "grade_level": 3,
     "text": "Regn ud: 36 + 42", "type": "calculation", "correct_answer": "78",
     "hints": ["Læg tierne sammen først"], "tags": "mental_matematik"},
    {"topic": "addition", "subtopic": "simpel", "difficulty": 1, "grade_level": 3,
     "text": "Regn ud: 51 + 28", "type": "calculation", "correct_answer": "79",
     "hints": ["1 + 8 = 9 i enerne"], "tags": "mental_matematik"},
    {"topic": "addition", "subtopic": "simpel", "difficulty": 1, "grade_level": 3,
     "text": "Regn ud: 63 + 25", "type": "calculation", "correct_answer": "88",
     "hints": ["3 + 5 = 8"], "tags": "mental_matematik"},
    {"topic": "addition", "subtopic": "simpel", "difficulty": 1, "grade_level": 3,
     "text": "Regn ud: 45 + 34", "type": "calculation", "correct_answer": "79",
     "hints": ["5 + 4 = 9"], "tags": "mental_matematik"},
    {"topic": "addition", "subtopic": "simpel", "difficulty": 1, "grade_level": 3,
     "text": "Regn ud: 17 + 52", "type": "calculation", "correct_answer": "69",
     "hints": ["7 + 2 = 9"], "tags": "mental_matematik"},
    # Difficulty 2 (4. klasse) — tierovergang
    {"topic": "addition", "subtopic": "tierovergang", "difficulty": 2, "grade_level": 4,
     "text": "Regn ud: 347 + 286", "type": "calculation", "correct_answer": "633",
     "hints": ["Skriv tallene under hinanden", "Start med enerne: 7 + 6 = 13"], "tags": "tierovergang,skriftlig"},
    {"topic": "addition", "subtopic": "tierovergang", "difficulty": 2, "grade_level": 4,
     "text": "Regn ud: 568 + 275", "type": "calculation", "correct_answer": "843",
     "hints": ["8 + 5 = 13, skriv 3, ment 1"], "tags": "tierovergang,skriftlig"},
    {"topic": "addition", "subtopic": "tierovergang", "difficulty": 2, "grade_level": 4,
     "text": "Regn ud: 459 + 387", "type": "calculation", "correct_answer": "846",
     "hints": ["9 + 7 = 16"], "tags": "tierovergang,skriftlig"},
    {"topic": "addition", "subtopic": "tierovergang", "difficulty": 2, "grade_level": 4,
     "text": "Regn ud: 694 + 238", "type": "calculation", "correct_answer": "932",
     "hints": ["4 + 8 = 12"], "tags": "tierovergang,skriftlig"},
    {"topic": "addition", "subtopic": "tierovergang", "difficulty": 2, "grade_level": 4,
     "text": "Regn ud: 178 + 456", "type": "calculation", "correct_answer": "634",
     "hints": ["8 + 6 = 14"], "tags": "tierovergang,skriftlig"},
    # Difficulty 3 (5. klasse) — store tal og tekstopgaver
    {"topic": "addition", "subtopic": "store_tal", "difficulty": 3, "grade_level": 5,
     "text": "Regn ud: 4.738 + 2.594", "type": "calculation", "correct_answer": "7332",
     "hints": ["Skriv tallene under hinanden", "Arbejd fra højre mod venstre"], "tags": "store_tal,skriftlig"},
    {"topic": "addition", "subtopic": "store_tal", "difficulty": 3, "grade_level": 5,
     "text": "Regn ud: 12.456 + 8.977", "type": "calculation", "correct_answer": "21433",
     "hints": ["Pas på tierovergangene"], "tags": "store_tal"},
    {"topic": "addition", "subtopic": "tekstopgave", "difficulty": 3, "grade_level": 5,
     "text": "Emma har 1.250 kr. Hun får 875 kr. i fødselsdagsgave. Hvor mange penge har hun nu?",
     "type": "word_problem", "correct_answer": "2125",
     "hints": ["Hvad skal du gøre med de to tal?", "Læg dem sammen"], "tags": "tekstopgave,penge"},
    {"topic": "addition", "subtopic": "tekstopgave", "difficulty": 3, "grade_level": 5,
     "text": "En bog har 234 sider. En anden bog har 189 sider. Hvor mange sider er der i alt?",
     "type": "word_problem", "correct_answer": "423",
     "hints": ["Find de to tal i opgaven"], "tags": "tekstopgave"},
    # Difficulty 4 (6. klasse)
    {"topic": "addition", "subtopic": "decimal", "difficulty": 4, "grade_level": 6,
     "text": "Regn ud: 23,47 + 8,65", "type": "calculation", "correct_answer": "32,12",
     "hints": ["Sæt kommaerne under hinanden"], "tags": "decimaltal"},
    {"topic": "addition", "subtopic": "decimal", "difficulty": 4, "grade_level": 6,
     "text": "Regn ud: 156,8 + 47,35", "type": "calculation", "correct_answer": "204,15",
     "hints": ["156,80 + 47,35 — tilføj et nul"], "tags": "decimaltal"},
    {"topic": "addition", "subtopic": "blandet", "difficulty": 4, "grade_level": 6,
     "text": "Regn ud: 34.567 + 28.945 + 12.388", "type": "calculation", "correct_answer": "75900",
     "hints": ["Læg de to første sammen først"], "tags": "store_tal"},
    # Additional
    {"topic": "addition", "subtopic": "simpel", "difficulty": 1, "grade_level": 3,
     "text": "Hvad er 99 + 1?", "type": "calculation", "correct_answer": "100",
     "hints": ["Tæl én op fra 99"], "tags": "mental_matematik"},
    {"topic": "addition", "subtopic": "tierovergang", "difficulty": 2, "grade_level": 4,
     "text": "Regn ud: 999 + 1", "type": "calculation", "correct_answer": "1000",
     "hints": ["Hvad sker der når alle cifre er 9?"], "tags": "tierovergang"},
    {"topic": "addition", "subtopic": "tekstopgave", "difficulty": 2, "grade_level": 4,
     "text": "Der er 145 elever i indskolingen og 278 i udskolingen. Hvor mange elever er der?",
     "type": "word_problem", "correct_answer": "423",
     "hints": ["Læg de to tal sammen"], "tags": "tekstopgave"},
    {"topic": "addition", "subtopic": "simpel", "difficulty": 1, "grade_level": 3,
     "text": "Regn ud: 50 + 30", "type": "calculation", "correct_answer": "80",
     "hints": ["5 tiere + 3 tiere"], "tags": "mental_matematik"},
    {"topic": "addition", "subtopic": "tierovergang", "difficulty": 2, "grade_level": 4,
     "text": "Regn ud: 486 + 357", "type": "calculation", "correct_answer": "843",
     "hints": ["6 + 7 = 13"], "tags": "tierovergang"},
    {"topic": "addition", "subtopic": "store_tal", "difficulty": 3, "grade_level": 5,
     "text": "Regn ud: 6.543 + 3.789", "type": "calculation", "correct_answer": "10332",
     "hints": ["3 + 9 = 12"], "tags": "store_tal"},
    {"topic": "addition", "subtopic": "decimal", "difficulty": 4, "grade_level": 6,
     "text": "Regn ud: 0,75 + 0,38", "type": "calculation", "correct_answer": "1,13",
     "hints": ["75 + 38 = 113, flyt kommaet"], "tags": "decimaltal"},

    # =========================================================================
    # SUBTRAKTION (25 problems)
    # =========================================================================
    {"topic": "subtraktion", "subtopic": "simpel", "difficulty": 1, "grade_level": 3,
     "text": "Regn ud: 87 - 35", "type": "calculation", "correct_answer": "52",
     "hints": ["7 - 5 = 2, 8 - 3 = 5"], "tags": "mental_matematik"},
    {"topic": "subtraktion", "subtopic": "simpel", "difficulty": 1, "grade_level": 3,
     "text": "Regn ud: 96 - 43", "type": "calculation", "correct_answer": "53",
     "hints": ["6 - 3 = 3"], "tags": "mental_matematik"},
    {"topic": "subtraktion", "subtopic": "simpel", "difficulty": 1, "grade_level": 3,
     "text": "Regn ud: 78 - 26", "type": "calculation", "correct_answer": "52",
     "hints": ["8 - 6 = 2"], "tags": "mental_matematik"},
    {"topic": "subtraktion", "subtopic": "simpel", "difficulty": 1, "grade_level": 3,
     "text": "Regn ud: 65 - 41", "type": "calculation", "correct_answer": "24",
     "hints": ["5 - 1 = 4, 6 - 4 = 2"], "tags": "mental_matematik"},
    {"topic": "subtraktion", "subtopic": "simpel", "difficulty": 1, "grade_level": 3,
     "text": "Regn ud: 100 - 37", "type": "calculation", "correct_answer": "63",
     "hints": ["100 - 30 = 70, 70 - 7 = 63"], "tags": "mental_matematik"},
    {"topic": "subtraktion", "subtopic": "tierovergang", "difficulty": 2, "grade_level": 4,
     "text": "Regn ud: 503 - 247", "type": "calculation", "correct_answer": "256",
     "hints": ["Du skal låne fra tierne"], "tags": "tierovergang,skriftlig"},
    {"topic": "subtraktion", "subtopic": "tierovergang", "difficulty": 2, "grade_level": 4,
     "text": "Regn ud: 812 - 456", "type": "calculation", "correct_answer": "356",
     "hints": ["2 - 6 går ikke, lån fra tierne"], "tags": "tierovergang,skriftlig"},
    {"topic": "subtraktion", "subtopic": "tierovergang", "difficulty": 2, "grade_level": 4,
     "text": "Regn ud: 700 - 283", "type": "calculation", "correct_answer": "417",
     "hints": ["Du skal låne to gange"], "tags": "tierovergang"},
    {"topic": "subtraktion", "subtopic": "tierovergang", "difficulty": 2, "grade_level": 4,
     "text": "Regn ud: 1000 - 456", "type": "calculation", "correct_answer": "544",
     "hints": ["Brug 999 - 456 + 1 som trick"], "tags": "tierovergang"},
    {"topic": "subtraktion", "subtopic": "tierovergang", "difficulty": 2, "grade_level": 4,
     "text": "Regn ud: 634 - 378", "type": "calculation", "correct_answer": "256",
     "hints": ["4 - 8 går ikke"], "tags": "tierovergang"},
    {"topic": "subtraktion", "subtopic": "store_tal", "difficulty": 3, "grade_level": 5,
     "text": "Regn ud: 8.435 - 3.678", "type": "calculation", "correct_answer": "4757",
     "hints": ["Skriv tallene under hinanden"], "tags": "store_tal"},
    {"topic": "subtraktion", "subtopic": "store_tal", "difficulty": 3, "grade_level": 5,
     "text": "Regn ud: 10.000 - 4.567", "type": "calculation", "correct_answer": "5433",
     "hints": ["Brug 9999 - 4567 + 1"], "tags": "store_tal"},
    {"topic": "subtraktion", "subtopic": "tekstopgave", "difficulty": 3, "grade_level": 5,
     "text": "Jonas har 2.500 kr. Han køber en cykel til 1.875 kr. Hvor mange penge har han tilbage?",
     "type": "word_problem", "correct_answer": "625",
     "hints": ["Træk prisen fra beløbet"], "tags": "tekstopgave,penge"},
    {"topic": "subtraktion", "subtopic": "tekstopgave", "difficulty": 3, "grade_level": 5,
     "text": "En tank rummer 5.000 liter. Der er brugt 3.245 liter. Hvor meget er der tilbage?",
     "type": "word_problem", "correct_answer": "1755",
     "hints": ["5000 - 3245"], "tags": "tekstopgave"},
    {"topic": "subtraktion", "subtopic": "decimal", "difficulty": 4, "grade_level": 6,
     "text": "Regn ud: 45,2 - 18,75", "type": "calculation", "correct_answer": "26,45",
     "hints": ["45,20 - 18,75"], "tags": "decimaltal"},
    {"topic": "subtraktion", "subtopic": "decimal", "difficulty": 4, "grade_level": 6,
     "text": "Regn ud: 100 - 37,85", "type": "calculation", "correct_answer": "62,15",
     "hints": ["100,00 - 37,85"], "tags": "decimaltal"},
    {"topic": "subtraktion", "subtopic": "simpel", "difficulty": 1, "grade_level": 3,
     "text": "Regn ud: 54 - 21", "type": "calculation", "correct_answer": "33",
     "hints": ["4 - 1 = 3"], "tags": "mental_matematik"},
    {"topic": "subtraktion", "subtopic": "tierovergang", "difficulty": 2, "grade_level": 4,
     "text": "Regn ud: 425 - 168", "type": "calculation", "correct_answer": "257",
     "hints": ["5 - 8 går ikke, lån"], "tags": "tierovergang"},
    {"topic": "subtraktion", "subtopic": "store_tal", "difficulty": 3, "grade_level": 5,
     "text": "Regn ud: 25.000 - 13.458", "type": "calculation", "correct_answer": "11542",
     "hints": ["Skriv tallene under hinanden"], "tags": "store_tal"},
    {"topic": "subtraktion", "subtopic": "blandet", "difficulty": 4, "grade_level": 6,
     "text": "Regn ud: 1.000.000 - 567.890", "type": "calculation", "correct_answer": "432110",
     "hints": ["Brug 999999 - 567890 + 1"], "tags": "store_tal"},
    {"topic": "subtraktion", "subtopic": "simpel", "difficulty": 1, "grade_level": 3,
     "text": "Hvad er 80 - 45?", "type": "calculation", "correct_answer": "35",
     "hints": ["80 - 40 = 40, 40 - 5 = 35"], "tags": "mental_matematik"},
    {"topic": "subtraktion", "subtopic": "tekstopgave", "difficulty": 2, "grade_level": 4,
     "text": "Der er 365 dage i et år. Der er gået 178 dage. Hvor mange dage er der tilbage?",
     "type": "word_problem", "correct_answer": "187",
     "hints": ["365 - 178"], "tags": "tekstopgave"},
    {"topic": "subtraktion", "subtopic": "simpel", "difficulty": 1, "grade_level": 3,
     "text": "Regn ud: 93 - 57", "type": "calculation", "correct_answer": "36",
     "hints": ["3 - 7 går ikke, lån fra tierne"], "tags": "tierovergang"},
    {"topic": "subtraktion", "subtopic": "decimal", "difficulty": 4, "grade_level": 6,
     "text": "Regn ud: 8,3 - 2,78", "type": "calculation", "correct_answer": "5,52",
     "hints": ["8,30 - 2,78"], "tags": "decimaltal"},
    {"topic": "subtraktion", "subtopic": "store_tal", "difficulty": 3, "grade_level": 5,
     "text": "Regn ud: 50.000 - 27.834", "type": "calculation", "correct_answer": "22166",
     "hints": ["Skriv tallene under hinanden"], "tags": "store_tal"},

    # =========================================================================
    # MULTIPLIKATION (25 problems)
    # =========================================================================
    {"topic": "multiplikation", "subtopic": "tabeller", "difficulty": 1, "grade_level": 3,
     "text": "Regn ud: 7 × 8", "type": "calculation", "correct_answer": "56",
     "hints": ["Tænk på 7-tabellen"], "tags": "tabeller"},
    {"topic": "multiplikation", "subtopic": "tabeller", "difficulty": 1, "grade_level": 3,
     "text": "Regn ud: 6 × 9", "type": "calculation", "correct_answer": "54",
     "hints": ["6 × 10 = 60, træk 6 fra"], "tags": "tabeller"},
    {"topic": "multiplikation", "subtopic": "tabeller", "difficulty": 1, "grade_level": 3,
     "text": "Regn ud: 8 × 5", "type": "calculation", "correct_answer": "40",
     "hints": ["5-tabellen er nem!"], "tags": "tabeller"},
    {"topic": "multiplikation", "subtopic": "tabeller", "difficulty": 1, "grade_level": 3,
     "text": "Regn ud: 9 × 9", "type": "calculation", "correct_answer": "81",
     "hints": ["9 × 10 - 9"], "tags": "tabeller"},
    {"topic": "multiplikation", "subtopic": "tabeller", "difficulty": 1, "grade_level": 3,
     "text": "Regn ud: 4 × 7", "type": "calculation", "correct_answer": "28",
     "hints": ["4 × 7 = 2 × 14"], "tags": "tabeller"},
    {"topic": "multiplikation", "subtopic": "tabeller", "difficulty": 1, "grade_level": 3,
     "text": "Regn ud: 3 × 12", "type": "calculation", "correct_answer": "36",
     "hints": ["3 × 10 + 3 × 2"], "tags": "tabeller"},
    {"topic": "multiplikation", "subtopic": "tocifret", "difficulty": 2, "grade_level": 4,
     "text": "Regn ud: 23 × 4", "type": "calculation", "correct_answer": "92",
     "hints": ["20 × 4 + 3 × 4"], "tags": "skriftlig"},
    {"topic": "multiplikation", "subtopic": "tocifret", "difficulty": 2, "grade_level": 4,
     "text": "Regn ud: 45 × 6", "type": "calculation", "correct_answer": "270",
     "hints": ["40 × 6 + 5 × 6"], "tags": "skriftlig"},
    {"topic": "multiplikation", "subtopic": "tocifret", "difficulty": 2, "grade_level": 4,
     "text": "Regn ud: 67 × 3", "type": "calculation", "correct_answer": "201",
     "hints": ["60 × 3 + 7 × 3"], "tags": "skriftlig"},
    {"topic": "multiplikation", "subtopic": "tocifret", "difficulty": 2, "grade_level": 4,
     "text": "Regn ud: 38 × 7", "type": "calculation", "correct_answer": "266",
     "hints": ["30 × 7 + 8 × 7"], "tags": "skriftlig"},
    {"topic": "multiplikation", "subtopic": "tocifret", "difficulty": 2, "grade_level": 4,
     "text": "Regn ud: 56 × 8", "type": "calculation", "correct_answer": "448",
     "hints": ["50 × 8 + 6 × 8"], "tags": "skriftlig"},
    {"topic": "multiplikation", "subtopic": "stor", "difficulty": 3, "grade_level": 5,
     "text": "Regn ud: 234 × 5", "type": "calculation", "correct_answer": "1170",
     "hints": ["200×5 + 30×5 + 4×5"], "tags": "skriftlig"},
    {"topic": "multiplikation", "subtopic": "stor", "difficulty": 3, "grade_level": 5,
     "text": "Regn ud: 125 × 8", "type": "calculation", "correct_answer": "1000",
     "hints": ["125 × 8 = 1000 — det er et fint tal!"], "tags": "skriftlig"},
    {"topic": "multiplikation", "subtopic": "tocifret_x_tocifret", "difficulty": 3, "grade_level": 5,
     "text": "Regn ud: 24 × 13", "type": "calculation", "correct_answer": "312",
     "hints": ["24×10 + 24×3"], "tags": "skriftlig"},
    {"topic": "multiplikation", "subtopic": "tocifret_x_tocifret", "difficulty": 3, "grade_level": 5,
     "text": "Regn ud: 36 × 25", "type": "calculation", "correct_answer": "900",
     "hints": ["36 × 25 = 9 × 4 × 25 = 9 × 100"], "tags": "skriftlig"},
    {"topic": "multiplikation", "subtopic": "tekstopgave", "difficulty": 3, "grade_level": 5,
     "text": "En klasse med 28 elever skal betale 45 kr. hver til en tur. Hvad koster det i alt?",
     "type": "word_problem", "correct_answer": "1260",
     "hints": ["28 × 45"], "tags": "tekstopgave,penge"},
    {"topic": "multiplikation", "subtopic": "stor", "difficulty": 4, "grade_level": 6,
     "text": "Regn ud: 456 × 23", "type": "calculation", "correct_answer": "10488",
     "hints": ["456×20 + 456×3"], "tags": "skriftlig"},
    {"topic": "multiplikation", "subtopic": "decimal", "difficulty": 4, "grade_level": 6,
     "text": "Regn ud: 3,5 × 4", "type": "calculation", "correct_answer": "14",
     "hints": ["35 × 4 = 140, flyt kommaet"], "tags": "decimaltal"},
    {"topic": "multiplikation", "subtopic": "decimal", "difficulty": 4, "grade_level": 6,
     "text": "Regn ud: 2,5 × 2,5", "type": "calculation", "correct_answer": "6,25",
     "hints": ["25 × 25 = 625, flyt kommaet to pladser"], "tags": "decimaltal"},
    {"topic": "multiplikation", "subtopic": "tabeller", "difficulty": 1, "grade_level": 3,
     "text": "Regn ud: 8 × 8", "type": "calculation", "correct_answer": "64",
     "hints": ["8-tabellen"], "tags": "tabeller"},
    {"topic": "multiplikation", "subtopic": "tabeller", "difficulty": 1, "grade_level": 3,
     "text": "Regn ud: 7 × 6", "type": "calculation", "correct_answer": "42",
     "hints": ["6 × 7 = 42 — svaret på alt!"], "tags": "tabeller"},
    {"topic": "multiplikation", "subtopic": "tocifret", "difficulty": 2, "grade_level": 4,
     "text": "Regn ud: 75 × 4", "type": "calculation", "correct_answer": "300",
     "hints": ["75 × 4 = 300 — et helt tal!"], "tags": "skriftlig"},
    {"topic": "multiplikation", "subtopic": "tekstopgave", "difficulty": 2, "grade_level": 4,
     "text": "Der er 9 rækker med 7 stole i hver. Hvor mange stole er der?",
     "type": "word_problem", "correct_answer": "63",
     "hints": ["9 × 7"], "tags": "tekstopgave,tabeller"},
    {"topic": "multiplikation", "subtopic": "stor", "difficulty": 3, "grade_level": 5,
     "text": "Regn ud: 15 × 15", "type": "calculation", "correct_answer": "225",
     "hints": ["15 × 15 = (15×10) + (15×5)"], "tags": "skriftlig"},
    {"topic": "multiplikation", "subtopic": "decimal", "difficulty": 4, "grade_level": 6,
     "text": "Regn ud: 0,6 × 0,8", "type": "calculation", "correct_answer": "0,48",
     "hints": ["6 × 8 = 48, to decimaler i alt"], "tags": "decimaltal"},

    # =========================================================================
    # DIVISION (25 problems)
    # =========================================================================
    {"topic": "division", "subtopic": "simpel", "difficulty": 1, "grade_level": 3,
     "text": "Regn ud: 56 ÷ 8", "type": "calculation", "correct_answer": "7",
     "hints": ["Hvad skal du gange 8 med for at få 56?"], "tags": "tabeller"},
    {"topic": "division", "subtopic": "simpel", "difficulty": 1, "grade_level": 3,
     "text": "Regn ud: 72 ÷ 9", "type": "calculation", "correct_answer": "8",
     "hints": ["9-tabellen baglæns"], "tags": "tabeller"},
    {"topic": "division", "subtopic": "simpel", "difficulty": 1, "grade_level": 3,
     "text": "Regn ud: 48 ÷ 6", "type": "calculation", "correct_answer": "8",
     "hints": ["6 × ? = 48"], "tags": "tabeller"},
    {"topic": "division", "subtopic": "simpel", "difficulty": 1, "grade_level": 3,
     "text": "Regn ud: 63 ÷ 7", "type": "calculation", "correct_answer": "9",
     "hints": ["7 × 9 = 63"], "tags": "tabeller"},
    {"topic": "division", "subtopic": "simpel", "difficulty": 1, "grade_level": 3,
     "text": "Regn ud: 45 ÷ 5", "type": "calculation", "correct_answer": "9",
     "hints": ["5-tabellen"], "tags": "tabeller"},
    {"topic": "division", "subtopic": "simpel", "difficulty": 1, "grade_level": 3,
     "text": "Regn ud: 36 ÷ 4", "type": "calculation", "correct_answer": "9",
     "hints": ["4 × 9 = 36"], "tags": "tabeller"},
    {"topic": "division", "subtopic": "kort_division", "difficulty": 2, "grade_level": 4,
     "text": "Regn ud: 84 ÷ 4", "type": "calculation", "correct_answer": "21",
     "hints": ["80 ÷ 4 = 20, 4 ÷ 4 = 1"], "tags": "kort_division"},
    {"topic": "division", "subtopic": "kort_division", "difficulty": 2, "grade_level": 4,
     "text": "Regn ud: 96 ÷ 3", "type": "calculation", "correct_answer": "32",
     "hints": ["90 ÷ 3 = 30, 6 ÷ 3 = 2"], "tags": "kort_division"},
    {"topic": "division", "subtopic": "kort_division", "difficulty": 2, "grade_level": 4,
     "text": "Regn ud: 156 ÷ 6", "type": "calculation", "correct_answer": "26",
     "hints": ["150 ÷ 6 = 25, 6 ÷ 6 = 1"], "tags": "kort_division"},
    {"topic": "division", "subtopic": "kort_division", "difficulty": 2, "grade_level": 4,
     "text": "Regn ud: 252 ÷ 7", "type": "calculation", "correct_answer": "36",
     "hints": ["210 ÷ 7 = 30, 42 ÷ 7 = 6"], "tags": "kort_division"},
    {"topic": "division", "subtopic": "kort_division", "difficulty": 2, "grade_level": 4,
     "text": "Regn ud: 135 ÷ 5", "type": "calculation", "correct_answer": "27",
     "hints": ["100 ÷ 5 = 20, 35 ÷ 5 = 7"], "tags": "kort_division"},
    {"topic": "division", "subtopic": "stor", "difficulty": 3, "grade_level": 5,
     "text": "Regn ud: 1.248 ÷ 8", "type": "calculation", "correct_answer": "156",
     "hints": ["Brug kort division"], "tags": "kort_division"},
    {"topic": "division", "subtopic": "stor", "difficulty": 3, "grade_level": 5,
     "text": "Regn ud: 2.340 ÷ 9", "type": "calculation", "correct_answer": "260",
     "hints": ["2340 ÷ 9"], "tags": "kort_division"},
    {"topic": "division", "subtopic": "tekstopgave", "difficulty": 3, "grade_level": 5,
     "text": "450 æbler skal deles ligeligt i 6 kasser. Hvor mange æbler er der i hver kasse?",
     "type": "word_problem", "correct_answer": "75",
     "hints": ["450 ÷ 6"], "tags": "tekstopgave"},
    {"topic": "division", "subtopic": "rest", "difficulty": 3, "grade_level": 5,
     "text": "Regn ud: 100 ÷ 7 (skriv rest)", "type": "calculation", "correct_answer": "14 rest 2",
     "hints": ["7 × 14 = 98, 100 - 98 = 2"], "tags": "rest"},
    {"topic": "division", "subtopic": "rest", "difficulty": 3, "grade_level": 5,
     "text": "Regn ud: 53 ÷ 8 (skriv rest)", "type": "calculation", "correct_answer": "6 rest 5",
     "hints": ["8 × 6 = 48, 53 - 48 = 5"], "tags": "rest"},
    {"topic": "division", "subtopic": "tocifret_divisor", "difficulty": 4, "grade_level": 6,
     "text": "Regn ud: 864 ÷ 12", "type": "calculation", "correct_answer": "72",
     "hints": ["Prøv: 12 × 70 = 840, 864 - 840 = 24, 24 ÷ 12 = 2"], "tags": "lang_division"},
    {"topic": "division", "subtopic": "tocifret_divisor", "difficulty": 4, "grade_level": 6,
     "text": "Regn ud: 1.575 ÷ 25", "type": "calculation", "correct_answer": "63",
     "hints": ["25 × 60 = 1500, 75 ÷ 25 = 3"], "tags": "lang_division"},
    {"topic": "division", "subtopic": "decimal", "difficulty": 4, "grade_level": 6,
     "text": "Regn ud: 7,5 ÷ 3", "type": "calculation", "correct_answer": "2,5",
     "hints": ["75 ÷ 3 = 25, flyt kommaet"], "tags": "decimaltal"},
    {"topic": "division", "subtopic": "decimal", "difficulty": 4, "grade_level": 6,
     "text": "Regn ud: 15,6 ÷ 4", "type": "calculation", "correct_answer": "3,9",
     "hints": ["156 ÷ 4 = 39"], "tags": "decimaltal"},
    {"topic": "division", "subtopic": "simpel", "difficulty": 1, "grade_level": 3,
     "text": "Regn ud: 81 ÷ 9", "type": "calculation", "correct_answer": "9",
     "hints": ["9 × 9 = 81"], "tags": "tabeller"},
    {"topic": "division", "subtopic": "tekstopgave", "difficulty": 2, "grade_level": 4,
     "text": "24 bolsjer skal deles ligeligt mellem 8 børn. Hvor mange får hver?",
     "type": "word_problem", "correct_answer": "3",
     "hints": ["24 ÷ 8"], "tags": "tekstopgave,tabeller"},
    {"topic": "division", "subtopic": "kort_division", "difficulty": 2, "grade_level": 4,
     "text": "Regn ud: 168 ÷ 8", "type": "calculation", "correct_answer": "21",
     "hints": ["160 ÷ 8 = 20, 8 ÷ 8 = 1"], "tags": "kort_division"},
    {"topic": "division", "subtopic": "stor", "difficulty": 3, "grade_level": 5,
     "text": "Regn ud: 3.600 ÷ 12", "type": "calculation", "correct_answer": "300",
     "hints": ["36 ÷ 12 = 3, tilføj to nuller"], "tags": "lang_division"},
    {"topic": "division", "subtopic": "tocifret_divisor", "difficulty": 4, "grade_level": 6,
     "text": "Regn ud: 2.048 ÷ 16", "type": "calculation", "correct_answer": "128",
     "hints": ["16 × 100 = 1600, 448 ÷ 16 = 28"], "tags": "lang_division"},

    # =========================================================================
    # BRØKER (25 problems)
    # =========================================================================
    {"topic": "broeker", "subtopic": "aflæsning", "difficulty": 1, "grade_level": 4,
     "text": "Hvad er halvdelen af 20?", "type": "calculation", "correct_answer": "10",
     "hints": ["½ × 20 = ?"], "tags": "simpel"},
    {"topic": "broeker", "subtopic": "aflæsning", "difficulty": 1, "grade_level": 4,
     "text": "Hvad er en fjerdedel af 24?", "type": "calculation", "correct_answer": "6",
     "hints": ["24 ÷ 4"], "tags": "simpel"},
    {"topic": "broeker", "subtopic": "aflæsning", "difficulty": 1, "grade_level": 4,
     "text": "Hvad er en tredjedel af 15?", "type": "calculation", "correct_answer": "5",
     "hints": ["15 ÷ 3"], "tags": "simpel"},
    {"topic": "broeker", "subtopic": "sammenligning", "difficulty": 2, "grade_level": 4,
     "text": "Hvad er størst: 2/3 eller 3/5?", "type": "calculation", "correct_answer": "2/3",
     "hints": ["Find fællesnævner: 15. 2/3 = 10/15, 3/5 = 9/15"], "tags": "sammenligning"},
    {"topic": "broeker", "subtopic": "sammenligning", "difficulty": 2, "grade_level": 4,
     "text": "Hvad er størst: 3/4 eller 5/8?", "type": "calculation", "correct_answer": "3/4",
     "hints": ["3/4 = 6/8"], "tags": "sammenligning"},
    {"topic": "broeker", "subtopic": "addition", "difficulty": 2, "grade_level": 5,
     "text": "Regn ud: 1/4 + 2/4", "type": "calculation", "correct_answer": "3/4",
     "hints": ["Samme nævner! Læg tællerne sammen"], "tags": "ens_naevner"},
    {"topic": "broeker", "subtopic": "addition", "difficulty": 2, "grade_level": 5,
     "text": "Regn ud: 3/8 + 2/8", "type": "calculation", "correct_answer": "5/8",
     "hints": ["Samme nævner: 3 + 2 = 5"], "tags": "ens_naevner"},
    {"topic": "broeker", "subtopic": "addition", "difficulty": 3, "grade_level": 5,
     "text": "Regn ud: 2/5 + 1/3", "type": "calculation", "correct_answer": "11/15",
     "hints": ["Fællesnævner for 5 og 3 er 15", "2/5 = 6/15, 1/3 = 5/15"], "tags": "faellesnaevner"},
    {"topic": "broeker", "subtopic": "addition", "difficulty": 3, "grade_level": 5,
     "text": "Regn ud: 1/2 + 1/3", "type": "calculation", "correct_answer": "5/6",
     "hints": ["Fællesnævner er 6", "1/2 = 3/6, 1/3 = 2/6"], "tags": "faellesnaevner"},
    {"topic": "broeker", "subtopic": "subtraktion", "difficulty": 3, "grade_level": 5,
     "text": "Regn ud: 3/4 - 1/3", "type": "calculation", "correct_answer": "5/12",
     "hints": ["Fællesnævner for 4 og 3 er 12", "9/12 - 4/12"], "tags": "faellesnaevner"},
    {"topic": "broeker", "subtopic": "subtraktion", "difficulty": 3, "grade_level": 5,
     "text": "Regn ud: 5/6 - 1/4", "type": "calculation", "correct_answer": "7/12",
     "hints": ["Fællesnævner er 12", "10/12 - 3/12"], "tags": "faellesnaevner"},
    {"topic": "broeker", "subtopic": "multiplikation", "difficulty": 3, "grade_level": 6,
     "text": "Regn ud: 2/3 × 3/4", "type": "calculation", "correct_answer": "1/2",
     "hints": ["Gang tæller med tæller og nævner med nævner", "6/12 = 1/2"], "tags": "gang"},
    {"topic": "broeker", "subtopic": "multiplikation", "difficulty": 3, "grade_level": 6,
     "text": "Regn ud: 3/5 × 5/6", "type": "calculation", "correct_answer": "1/2",
     "hints": ["15/30 = 1/2"], "tags": "gang"},
    {"topic": "broeker", "subtopic": "af_et_tal", "difficulty": 2, "grade_level": 5,
     "text": "Hvad er 3/4 af 60?", "type": "calculation", "correct_answer": "45",
     "hints": ["60 ÷ 4 = 15, 15 × 3 = 45"], "tags": "af"},
    {"topic": "broeker", "subtopic": "af_et_tal", "difficulty": 2, "grade_level": 5,
     "text": "Hvad er 2/5 af 100?", "type": "calculation", "correct_answer": "40",
     "hints": ["100 ÷ 5 = 20, 20 × 2 = 40"], "tags": "af"},
    {"topic": "broeker", "subtopic": "forenkling", "difficulty": 3, "grade_level": 5,
     "text": "Forkort brøken 12/18", "type": "calculation", "correct_answer": "2/3",
     "hints": ["Find den største fælles divisor", "Begge kan deles med 6"], "tags": "forenkling"},
    {"topic": "broeker", "subtopic": "forenkling", "difficulty": 3, "grade_level": 5,
     "text": "Forkort brøken 15/25", "type": "calculation", "correct_answer": "3/5",
     "hints": ["Begge kan deles med 5"], "tags": "forenkling"},
    {"topic": "broeker", "subtopic": "uægte", "difficulty": 3, "grade_level": 6,
     "text": "Omskriv 7/4 til blandet tal", "type": "calculation", "correct_answer": "1 3/4",
     "hints": ["7 ÷ 4 = 1 rest 3"], "tags": "blandet_tal"},
    {"topic": "broeker", "subtopic": "uægte", "difficulty": 3, "grade_level": 6,
     "text": "Omskriv 11/3 til blandet tal", "type": "calculation", "correct_answer": "3 2/3",
     "hints": ["11 ÷ 3 = 3 rest 2"], "tags": "blandet_tal"},
    {"topic": "broeker", "subtopic": "tekstopgave", "difficulty": 3, "grade_level": 5,
     "text": "En pizza er delt i 8 stykker. Du spiser 3. Hvor stor en del har du spist?",
     "type": "word_problem", "correct_answer": "3/8",
     "hints": ["Du spiste 3 ud af 8 stykker"], "tags": "tekstopgave"},
    {"topic": "broeker", "subtopic": "tekstopgave", "difficulty": 4, "grade_level": 6,
     "text": "En klasse har 30 elever. 2/5 spiller fodbold. Hvor mange spiller fodbold?",
     "type": "word_problem", "correct_answer": "12",
     "hints": ["2/5 af 30 = ?", "30 ÷ 5 = 6, 6 × 2 = 12"], "tags": "tekstopgave,af"},
    {"topic": "broeker", "subtopic": "aflæsning", "difficulty": 1, "grade_level": 4,
     "text": "Hvad er halvdelen af 50?", "type": "calculation", "correct_answer": "25",
     "hints": ["50 ÷ 2"], "tags": "simpel"},
    {"topic": "broeker", "subtopic": "addition", "difficulty": 2, "grade_level": 5,
     "text": "Regn ud: 1/6 + 2/6", "type": "calculation", "correct_answer": "3/6",
     "hints": ["Samme nævner: 1 + 2 = 3", "Kan forkortes til 1/2"], "tags": "ens_naevner"},
    {"topic": "broeker", "subtopic": "division", "difficulty": 4, "grade_level": 6,
     "text": "Regn ud: 3/4 ÷ 1/2", "type": "calculation", "correct_answer": "3/2",
     "hints": ["Del med en brøk = gang med den omvendte", "3/4 × 2/1"], "tags": "division"},
    {"topic": "broeker", "subtopic": "af_et_tal", "difficulty": 2, "grade_level": 5,
     "text": "Hvad er 1/3 af 90?", "type": "calculation", "correct_answer": "30",
     "hints": ["90 ÷ 3"], "tags": "af"},

    # =========================================================================
    # DECIMALTAL (20 problems)
    # =========================================================================
    {"topic": "decimaltal", "subtopic": "aflæsning", "difficulty": 1, "grade_level": 4,
     "text": "Hvad er 0,5 som brøk?", "type": "calculation", "correct_answer": "1/2",
     "hints": ["0,5 = 5/10 = 1/2"], "tags": "konvertering"},
    {"topic": "decimaltal", "subtopic": "aflæsning", "difficulty": 1, "grade_level": 4,
     "text": "Hvad er 0,25 som brøk?", "type": "calculation", "correct_answer": "1/4",
     "hints": ["0,25 = 25/100 = 1/4"], "tags": "konvertering"},
    {"topic": "decimaltal", "subtopic": "addition", "difficulty": 2, "grade_level": 5,
     "text": "Regn ud: 3,4 + 2,8", "type": "calculation", "correct_answer": "6,2",
     "hints": ["4 + 8 = 12, skriv 2, ment 1"], "tags": "addition"},
    {"topic": "decimaltal", "subtopic": "addition", "difficulty": 2, "grade_level": 5,
     "text": "Regn ud: 12,65 + 7,48", "type": "calculation", "correct_answer": "20,13",
     "hints": ["Sæt kommaerne under hinanden"], "tags": "addition"},
    {"topic": "decimaltal", "subtopic": "subtraktion", "difficulty": 2, "grade_level": 5,
     "text": "Regn ud: 8,5 - 3,7", "type": "calculation", "correct_answer": "4,8",
     "hints": ["5 - 7 går ikke, lån"], "tags": "subtraktion"},
    {"topic": "decimaltal", "subtopic": "subtraktion", "difficulty": 2, "grade_level": 5,
     "text": "Regn ud: 15,3 - 8,75", "type": "calculation", "correct_answer": "6,55",
     "hints": ["15,30 - 8,75"], "tags": "subtraktion"},
    {"topic": "decimaltal", "subtopic": "multiplikation", "difficulty": 3, "grade_level": 5,
     "text": "Regn ud: 4,2 × 3", "type": "calculation", "correct_answer": "12,6",
     "hints": ["42 × 3 = 126, flyt kommaet"], "tags": "multiplikation"},
    {"topic": "decimaltal", "subtopic": "multiplikation", "difficulty": 3, "grade_level": 6,
     "text": "Regn ud: 1,5 × 1,5", "type": "calculation", "correct_answer": "2,25",
     "hints": ["15 × 15 = 225, to decimaler"], "tags": "multiplikation"},
    {"topic": "decimaltal", "subtopic": "afrunding", "difficulty": 2, "grade_level": 5,
     "text": "Afrund 7,38 til én decimal", "type": "calculation", "correct_answer": "7,4",
     "hints": ["Kig på andendecimalen: 8 ≥ 5, rund op"], "tags": "afrunding"},
    {"topic": "decimaltal", "subtopic": "afrunding", "difficulty": 2, "grade_level": 5,
     "text": "Afrund 12,345 til hele tal", "type": "calculation", "correct_answer": "12",
     "hints": ["3 < 5, rund ned"], "tags": "afrunding"},
    {"topic": "decimaltal", "subtopic": "sammenligning", "difficulty": 2, "grade_level": 5,
     "text": "Hvad er størst: 0,7 eller 0,65?", "type": "calculation", "correct_answer": "0,7",
     "hints": ["0,7 = 0,70 — sammenlign nu"], "tags": "sammenligning"},
    {"topic": "decimaltal", "subtopic": "sammenligning", "difficulty": 2, "grade_level": 5,
     "text": "Sæt i rækkefølge fra mindst til størst: 0,3  0,25  0,35", "type": "calculation",
     "correct_answer": "0,25  0,3  0,35",
     "hints": ["Gør dem alle til hundrededele: 30, 25, 35"], "tags": "sammenligning"},
    {"topic": "decimaltal", "subtopic": "division", "difficulty": 3, "grade_level": 6,
     "text": "Regn ud: 9,6 ÷ 4", "type": "calculation", "correct_answer": "2,4",
     "hints": ["96 ÷ 4 = 24, flyt kommaet"], "tags": "division"},
    {"topic": "decimaltal", "subtopic": "division", "difficulty": 3, "grade_level": 6,
     "text": "Regn ud: 14,7 ÷ 3", "type": "calculation", "correct_answer": "4,9",
     "hints": ["147 ÷ 3 = 49"], "tags": "division"},
    {"topic": "decimaltal", "subtopic": "tekstopgave", "difficulty": 3, "grade_level": 5,
     "text": "En liter mælk koster 12,50 kr. Hvad koster 3 liter?",
     "type": "word_problem", "correct_answer": "37,50",
     "hints": ["12,50 × 3"], "tags": "tekstopgave,penge"},
    {"topic": "decimaltal", "subtopic": "tekstopgave", "difficulty": 3, "grade_level": 6,
     "text": "Du betaler 50 kr. for noget der koster 33,75 kr. Hvor meget får du tilbage?",
     "type": "word_problem", "correct_answer": "16,25",
     "hints": ["50,00 - 33,75"], "tags": "tekstopgave,penge"},
    {"topic": "decimaltal", "subtopic": "konvertering", "difficulty": 2, "grade_level": 5,
     "text": "Skriv 3/4 som decimaltal", "type": "calculation", "correct_answer": "0,75",
     "hints": ["3 ÷ 4 = 0,75"], "tags": "konvertering"},
    {"topic": "decimaltal", "subtopic": "konvertering", "difficulty": 2, "grade_level": 5,
     "text": "Skriv 1/5 som decimaltal", "type": "calculation", "correct_answer": "0,2",
     "hints": ["1 ÷ 5 = 0,2"], "tags": "konvertering"},
    {"topic": "decimaltal", "subtopic": "addition", "difficulty": 2, "grade_level": 5,
     "text": "Regn ud: 0,99 + 0,01", "type": "calculation", "correct_answer": "1",
     "hints": ["99 + 1 = 100 hundrededele = 1"], "tags": "addition"},
    {"topic": "decimaltal", "subtopic": "multiplikation", "difficulty": 3, "grade_level": 6,
     "text": "Regn ud: 0,3 × 0,4", "type": "calculation", "correct_answer": "0,12",
     "hints": ["3 × 4 = 12, to decimaler i alt"], "tags": "multiplikation"},

    # =========================================================================
    # GEOMETRI (25 problems)
    # =========================================================================
    {"topic": "geometri", "subtopic": "omkreds", "difficulty": 1, "grade_level": 3,
     "text": "Et rektangel er 8 cm langt og 5 cm bredt. Hvad er omkredsen?",
     "type": "calculation", "correct_answer": "26 cm",
     "hints": ["Omkreds = 2 × (længde + bredde)", "2 × (8 + 5)"], "tags": "rektangel,omkreds"},
    {"topic": "geometri", "subtopic": "omkreds", "difficulty": 1, "grade_level": 3,
     "text": "Et kvadrat har sidelængde 6 cm. Hvad er omkredsen?",
     "type": "calculation", "correct_answer": "24 cm",
     "hints": ["4 × 6"], "tags": "kvadrat,omkreds"},
    {"topic": "geometri", "subtopic": "areal", "difficulty": 2, "grade_level": 4,
     "text": "Et rektangel er 12 cm langt og 7 cm bredt. Hvad er arealet?",
     "type": "calculation", "correct_answer": "84 cm²",
     "hints": ["Areal = længde × bredde", "12 × 7"], "tags": "rektangel,areal"},
    {"topic": "geometri", "subtopic": "areal", "difficulty": 2, "grade_level": 4,
     "text": "Et kvadrat har sidelængde 9 cm. Hvad er arealet?",
     "type": "calculation", "correct_answer": "81 cm²",
     "hints": ["Areal = side × side", "9 × 9"], "tags": "kvadrat,areal"},
    {"topic": "geometri", "subtopic": "areal", "difficulty": 2, "grade_level": 4,
     "text": "En trekant har grundlinje 10 cm og højde 6 cm. Hvad er arealet?",
     "type": "calculation", "correct_answer": "30 cm²",
     "hints": ["Areal = ½ × grundlinje × højde", "½ × 10 × 6"], "tags": "trekant,areal"},
    {"topic": "geometri", "subtopic": "areal", "difficulty": 3, "grade_level": 5,
     "text": "En trekant har grundlinje 15 cm og højde 8 cm. Hvad er arealet?",
     "type": "calculation", "correct_answer": "60 cm²",
     "hints": ["½ × 15 × 8"], "tags": "trekant,areal"},
    {"topic": "geometri", "subtopic": "omkreds_cirkel", "difficulty": 3, "grade_level": 6,
     "text": "En cirkel har radius 7 cm. Hvad er omkredsen? (brug π ≈ 3,14)",
     "type": "calculation", "correct_answer": "43,96 cm",
     "hints": ["Omkreds = 2 × π × r", "2 × 3,14 × 7"], "tags": "cirkel,omkreds"},
    {"topic": "geometri", "subtopic": "areal_cirkel", "difficulty": 3, "grade_level": 6,
     "text": "En cirkel har radius 5 cm. Hvad er arealet? (brug π ≈ 3,14)",
     "type": "calculation", "correct_answer": "78,5 cm²",
     "hints": ["Areal = π × r²", "3,14 × 25"], "tags": "cirkel,areal"},
    {"topic": "geometri", "subtopic": "vinkel", "difficulty": 2, "grade_level": 5,
     "text": "I en trekant er to vinkler 60° og 80°. Hvad er den tredje vinkel?",
     "type": "calculation", "correct_answer": "40°",
     "hints": ["Vinklerne i en trekant er 180° tilsammen", "180 - 60 - 80"], "tags": "vinkel,trekant"},
    {"topic": "geometri", "subtopic": "vinkel", "difficulty": 2, "grade_level": 5,
     "text": "I en trekant er to vinkler 45° og 90°. Hvad er den tredje vinkel?",
     "type": "calculation", "correct_answer": "45°",
     "hints": ["180 - 45 - 90"], "tags": "vinkel,trekant"},
    {"topic": "geometri", "subtopic": "rumfang", "difficulty": 3, "grade_level": 6,
     "text": "En kasse er 10 cm lang, 5 cm bred og 3 cm høj. Hvad er rumfanget?",
     "type": "calculation", "correct_answer": "150 cm³",
     "hints": ["Rumfang = længde × bredde × højde", "10 × 5 × 3"], "tags": "rumfang,kasse"},
    {"topic": "geometri", "subtopic": "rumfang", "difficulty": 3, "grade_level": 6,
     "text": "En terning har sidelængde 4 cm. Hvad er rumfanget?",
     "type": "calculation", "correct_answer": "64 cm³",
     "hints": ["4 × 4 × 4"], "tags": "rumfang,terning"},
    {"topic": "geometri", "subtopic": "tekstopgave", "difficulty": 2, "grade_level": 4,
     "text": "Et rum er 6 m langt og 4 m bredt. Hvor stort er gulvarealet?",
     "type": "word_problem", "correct_answer": "24 m²",
     "hints": ["6 × 4"], "tags": "tekstopgave,areal"},
    {"topic": "geometri", "subtopic": "tekstopgave", "difficulty": 3, "grade_level": 5,
     "text": "Et hegn skal sættes rundt om en have der er 15 m lang og 10 m bred. Hvor mange meter hegn?",
     "type": "word_problem", "correct_answer": "50 m",
     "hints": ["Omkreds = 2 × (15 + 10)"], "tags": "tekstopgave,omkreds"},
    {"topic": "geometri", "subtopic": "omkreds", "difficulty": 1, "grade_level": 3,
     "text": "Et rektangel er 10 cm langt og 3 cm bredt. Hvad er omkredsen?",
     "type": "calculation", "correct_answer": "26 cm",
     "hints": ["2 × (10 + 3)"], "tags": "rektangel,omkreds"},
    {"topic": "geometri", "subtopic": "areal", "difficulty": 2, "grade_level": 4,
     "text": "Et rektangel er 20 cm langt og 5 cm bredt. Hvad er arealet?",
     "type": "calculation", "correct_answer": "100 cm²",
     "hints": ["20 × 5"], "tags": "rektangel,areal"},
    {"topic": "geometri", "subtopic": "symmetri", "difficulty": 1, "grade_level": 3,
     "text": "Hvor mange symmetrilinjer har et kvadrat?", "type": "calculation", "correct_answer": "4",
     "hints": ["Tænk på lodret, vandret og de to diagonaler"], "tags": "symmetri"},
    {"topic": "geometri", "subtopic": "areal_cirkel", "difficulty": 4, "grade_level": 6,
     "text": "En cirkel har diameter 10 cm. Hvad er arealet? (brug π ≈ 3,14)",
     "type": "calculation", "correct_answer": "78,5 cm²",
     "hints": ["Radius = 5 cm", "π × 5²"], "tags": "cirkel,areal"},
    {"topic": "geometri", "subtopic": "tekstopgave", "difficulty": 3, "grade_level": 6,
     "text": "Et svømmebassin er 25 m langt, 10 m bredt og 2 m dybt. Hvor mange liter vand kan det rumme?",
     "type": "word_problem", "correct_answer": "500000",
     "hints": ["Rumfang = 25×10×2 = 500 m³", "1 m³ = 1000 liter"], "tags": "tekstopgave,rumfang"},
    {"topic": "geometri", "subtopic": "koordinater", "difficulty": 2, "grade_level": 5,
     "text": "Hvad er afstanden fra (0,0) til (3,4)?", "type": "calculation", "correct_answer": "5",
     "hints": ["Brug Pythagoras: √(3² + 4²)", "√(9+16) = √25"], "tags": "koordinater"},
    {"topic": "geometri", "subtopic": "omkreds", "difficulty": 1, "grade_level": 3,
     "text": "En ligebenet trekant har to sider på 7 cm og en side på 10 cm. Hvad er omkredsen?",
     "type": "calculation", "correct_answer": "24 cm",
     "hints": ["7 + 7 + 10"], "tags": "trekant,omkreds"},
    {"topic": "geometri", "subtopic": "areal", "difficulty": 2, "grade_level": 5,
     "text": "Et parallelogram har grundlinje 12 cm og højde 5 cm. Hvad er arealet?",
     "type": "calculation", "correct_answer": "60 cm²",
     "hints": ["Areal = grundlinje × højde"], "tags": "parallelogram,areal"},
    {"topic": "geometri", "subtopic": "rumfang", "difficulty": 4, "grade_level": 6,
     "text": "En cylinder har radius 3 cm og højde 10 cm. Hvad er rumfanget? (brug π ≈ 3,14)",
     "type": "calculation", "correct_answer": "282,6 cm³",
     "hints": ["V = π × r² × h", "3,14 × 9 × 10"], "tags": "cylinder,rumfang"},
    {"topic": "geometri", "subtopic": "vinkel", "difficulty": 2, "grade_level": 5,
     "text": "Hvad er summen af vinklerne i en firkant?", "type": "calculation", "correct_answer": "360°",
     "hints": ["En firkant kan deles i to trekanter", "2 × 180°"], "tags": "vinkel"},
    {"topic": "geometri", "subtopic": "tekstopgave", "difficulty": 2, "grade_level": 4,
     "text": "Et rektangulært flag er 90 cm × 60 cm. Hvad er arealet i m²?",
     "type": "word_problem", "correct_answer": "0,54 m²",
     "hints": ["0,9 m × 0,6 m = 0,54 m²"], "tags": "tekstopgave,areal,enheder"},

    # =========================================================================
    # LIGNINGER (15 problems)
    # =========================================================================
    {"topic": "ligninger", "subtopic": "find_x", "difficulty": 2, "grade_level": 5,
     "text": "Find x: x + 7 = 15", "type": "equation", "correct_answer": "8",
     "hints": ["Hvad plus 7 giver 15?", "x = 15 - 7"], "tags": "simpel"},
    {"topic": "ligninger", "subtopic": "find_x", "difficulty": 2, "grade_level": 5,
     "text": "Find x: x - 12 = 25", "type": "equation", "correct_answer": "37",
     "hints": ["x = 25 + 12"], "tags": "simpel"},
    {"topic": "ligninger", "subtopic": "find_x", "difficulty": 2, "grade_level": 5,
     "text": "Find x: 3 × x = 24", "type": "equation", "correct_answer": "8",
     "hints": ["x = 24 ÷ 3"], "tags": "simpel"},
    {"topic": "ligninger", "subtopic": "find_x", "difficulty": 2, "grade_level": 5,
     "text": "Find x: x ÷ 5 = 9", "type": "equation", "correct_answer": "45",
     "hints": ["x = 9 × 5"], "tags": "simpel"},
    {"topic": "ligninger", "subtopic": "find_x", "difficulty": 2, "grade_level": 5,
     "text": "Find x: 2 × x + 3 = 11", "type": "equation", "correct_answer": "4",
     "hints": ["2x = 11 - 3 = 8", "x = 8 ÷ 2"], "tags": "to_trin"},
    {"topic": "ligninger", "subtopic": "find_x", "difficulty": 3, "grade_level": 6,
     "text": "Find x: 4x - 7 = 21", "type": "equation", "correct_answer": "7",
     "hints": ["4x = 21 + 7 = 28", "x = 28 ÷ 4"], "tags": "to_trin"},
    {"topic": "ligninger", "subtopic": "find_x", "difficulty": 3, "grade_level": 6,
     "text": "Find x: 5x + 10 = 35", "type": "equation", "correct_answer": "5",
     "hints": ["5x = 35 - 10 = 25", "x = 25 ÷ 5"], "tags": "to_trin"},
    {"topic": "ligninger", "subtopic": "find_x", "difficulty": 3, "grade_level": 6,
     "text": "Find x: 3(x + 2) = 18", "type": "equation", "correct_answer": "4",
     "hints": ["x + 2 = 18 ÷ 3 = 6", "x = 6 - 2"], "tags": "parentes"},
    {"topic": "ligninger", "subtopic": "find_x", "difficulty": 4, "grade_level": 6,
     "text": "Find x: 2x + 5 = x + 12", "type": "equation", "correct_answer": "7",
     "hints": ["2x - x = 12 - 5", "x = 7"], "tags": "x_begge_sider"},
    {"topic": "ligninger", "subtopic": "tekstopgave", "difficulty": 3, "grade_level": 6,
     "text": "Et tal ganget med 6 minus 4 giver 20. Hvad er tallet?",
     "type": "word_problem", "correct_answer": "4",
     "hints": ["6x - 4 = 20", "6x = 24"], "tags": "tekstopgave"},
    {"topic": "ligninger", "subtopic": "find_x", "difficulty": 2, "grade_level": 5,
     "text": "Find x: x + x = 18", "type": "equation", "correct_answer": "9",
     "hints": ["2x = 18"], "tags": "simpel"},
    {"topic": "ligninger", "subtopic": "find_x", "difficulty": 2, "grade_level": 5,
     "text": "Find det manglende tal: __ + 9 = 13", "type": "equation", "correct_answer": "4",
     "hints": ["13 - 9 = ?"], "tags": "simpel,manglende_tal"},
    {"topic": "ligninger", "subtopic": "find_x", "difficulty": 2, "grade_level": 5,
     "text": "Find det manglende tal: __ × 7 = 42", "type": "equation", "correct_answer": "6",
     "hints": ["42 ÷ 7"], "tags": "simpel,manglende_tal"},
    {"topic": "ligninger", "subtopic": "find_x", "difficulty": 3, "grade_level": 6,
     "text": "Find x: x/3 + 5 = 9", "type": "equation", "correct_answer": "12",
     "hints": ["x/3 = 9 - 5 = 4", "x = 4 × 3"], "tags": "to_trin"},
    {"topic": "ligninger", "subtopic": "tekstopgave", "difficulty": 3, "grade_level": 6,
     "text": "Sofie har dobbelt så mange penge som Emil. Tilsammen har de 45 kr. Hvor mange har Emil?",
     "type": "word_problem", "correct_answer": "15",
     "hints": ["Emil = x, Sofie = 2x", "x + 2x = 45, 3x = 45"], "tags": "tekstopgave"},

    # =========================================================================
    # PROCENT (15 problems)
    # =========================================================================
    {"topic": "procent", "subtopic": "af_et_tal", "difficulty": 2, "grade_level": 5,
     "text": "Hvad er 50% af 80?", "type": "calculation", "correct_answer": "40",
     "hints": ["50% = halvdelen"], "tags": "simpel"},
    {"topic": "procent", "subtopic": "af_et_tal", "difficulty": 2, "grade_level": 5,
     "text": "Hvad er 25% af 200?", "type": "calculation", "correct_answer": "50",
     "hints": ["25% = en fjerdedel", "200 ÷ 4"], "tags": "simpel"},
    {"topic": "procent", "subtopic": "af_et_tal", "difficulty": 2, "grade_level": 5,
     "text": "Hvad er 10% af 350?", "type": "calculation", "correct_answer": "35",
     "hints": ["10% = dél med 10"], "tags": "simpel"},
    {"topic": "procent", "subtopic": "af_et_tal", "difficulty": 3, "grade_level": 6,
     "text": "Hvad er 15% af 200?", "type": "calculation", "correct_answer": "30",
     "hints": ["10% = 20, 5% = 10, 15% = 30"], "tags": "beregning"},
    {"topic": "procent", "subtopic": "af_et_tal", "difficulty": 3, "grade_level": 6,
     "text": "Hvad er 30% af 150?", "type": "calculation", "correct_answer": "45",
     "hints": ["10% = 15, 30% = 3 × 15"], "tags": "beregning"},
    {"topic": "procent", "subtopic": "find_procent", "difficulty": 3, "grade_level": 6,
     "text": "12 ud af 48 — hvor mange procent?", "type": "calculation", "correct_answer": "25%",
     "hints": ["12/48 = 1/4 = 25%"], "tags": "beregning"},
    {"topic": "procent", "subtopic": "find_procent", "difficulty": 3, "grade_level": 6,
     "text": "15 ud af 60 — hvor mange procent?", "type": "calculation", "correct_answer": "25%",
     "hints": ["15/60 = 1/4"], "tags": "beregning"},
    {"topic": "procent", "subtopic": "rabat", "difficulty": 3, "grade_level": 6,
     "text": "En jakke koster 400 kr. Der er 20% rabat. Hvad er den nye pris?",
     "type": "word_problem", "correct_answer": "320",
     "hints": ["20% af 400 = 80 kr. rabat", "400 - 80"], "tags": "tekstopgave,rabat"},
    {"topic": "procent", "subtopic": "rabat", "difficulty": 3, "grade_level": 6,
     "text": "Et spil koster 250 kr. med 10% rabat. Hvad skal du betale?",
     "type": "word_problem", "correct_answer": "225",
     "hints": ["10% af 250 = 25", "250 - 25"], "tags": "tekstopgave,rabat"},
    {"topic": "procent", "subtopic": "stigning", "difficulty": 4, "grade_level": 6,
     "text": "En vare stiger 25% fra 80 kr. Hvad koster den nu?",
     "type": "word_problem", "correct_answer": "100",
     "hints": ["25% af 80 = 20", "80 + 20"], "tags": "tekstopgave,stigning"},
    {"topic": "procent", "subtopic": "tekstopgave", "difficulty": 3, "grade_level": 6,
     "text": "Der er 30 elever i en klasse. 60% er piger. Hvor mange piger er der?",
     "type": "word_problem", "correct_answer": "18",
     "hints": ["60% af 30", "0,6 × 30"], "tags": "tekstopgave"},
    {"topic": "procent", "subtopic": "af_et_tal", "difficulty": 2, "grade_level": 5,
     "text": "Hvad er 75% af 40?", "type": "calculation", "correct_answer": "30",
     "hints": ["75% = 3/4", "40 ÷ 4 × 3"], "tags": "simpel"},
    {"topic": "procent", "subtopic": "konvertering", "difficulty": 2, "grade_level": 5,
     "text": "Skriv 3/5 som procent", "type": "calculation", "correct_answer": "60%",
     "hints": ["3 ÷ 5 = 0,6 = 60%"], "tags": "konvertering"},
    {"topic": "procent", "subtopic": "konvertering", "difficulty": 2, "grade_level": 5,
     "text": "Skriv 0,45 som procent", "type": "calculation", "correct_answer": "45%",
     "hints": ["Gang med 100"], "tags": "konvertering"},
    {"topic": "procent", "subtopic": "tekstopgave", "difficulty": 4, "grade_level": 6,
     "text": "En cykel koster 3.000 kr. Du har sparet 40%. Hvor meget mangler du?",
     "type": "word_problem", "correct_answer": "1800",
     "hints": ["40% sparet = 60% mangler", "60% af 3000 = 1800"], "tags": "tekstopgave"},
]

# Topic display names and icons
TOPIC_META = {
    "addition": {"name": "Addition", "icon": "plus.circle.fill"},
    "subtraktion": {"name": "Subtraktion", "icon": "minus.circle.fill"},
    "multiplikation": {"name": "Multiplikation", "icon": "multiply.circle.fill"},
    "division": {"name": "Division", "icon": "divide.circle.fill"},
    "broeker": {"name": "Brøker", "icon": "chart.pie.fill"},
    "decimaltal": {"name": "Decimaltal", "icon": "number.circle.fill"},
    "geometri": {"name": "Geometri", "icon": "triangle.fill"},
    "ligninger": {"name": "Ligninger", "icon": "x.squareroot"},
    "procent": {"name": "Procent", "icon": "percent"},
}


def seed_math_problems(db) -> int:
    """Insert seed problems into the database. Returns count of inserted problems."""
    count = 0
    for p in PROBLEMS:
        problem = MathProblem(
            topic=p["topic"],
            subtopic=p.get("subtopic", ""),
            difficulty=p["difficulty"],
            grade_level=p["grade_level"],
            text=p["text"],
            type=p["type"],
            correct_answer=p["correct_answer"],
            solution_steps=p.get("solution_steps"),
            hints=p.get("hints"),
            tags=p.get("tags", ""),
        )
        db.add(problem)
        count += 1
    db.commit()
    logger.info("Seeded %d math problems", count)
    return count
